/** Chennai area names for Egmore page copy (no Virugambakkam). */
export const EGMORE_AREA_NAMES = [
  'Chennai',
  'T Nagar',
  'Adyar',
  'Alwarpet',
  'Anna nagar',
  'Besant nagar',
  'Harrington',
  'Koyambedu',
  'Chepauk',
  'Egmore',
  'Kotturpuram',
  'Marina beach',
  'Mylapore',
  'Nelson Manickam Road',
  'RA Puram',
  'Teynampet',
  'Thiruvalluvar',
  'Thiruvanmiyur',
  'Vadapalani',
  'Valarpuram',
  'Valluvar kottam',
  'Nungambakkam',
  'Boat Club Road',
  'Poes Garden',
  'Gopalapuram',
  'Royapettah',
  'Porur',
  'Velachery',
  'Omr Road',
  'Ecr Road',
  'Taramani',
  'Ekkattuthangal',
  'Guindy',
  'Saidapet',
  'KK Nagar',
  'Sholinganallur',
  'Tambaram',
  'Thoraipakkam',
  'Alandur',
  'Madipakkam',
  'Mahabalipuram',
  'Manapakkam',
  'Mount Road',
  'Ambattur',
  'Neelankarai',
  'Pallavaram',
  'Pallikaranai',
  'Perungudi',
  'Poonamallee',
  'Avadi',
  'Chetpet',
  'Abhiramapuram',
  'Kilpauk',
  'Mandaveli',
  'Nandanam',
] as const;
